const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// POST /api/report/generate-pdf
router.post('/generate-pdf', async (req, res) => {
  try {
    const { assessmentData, userInfo } = req.body;
    
    const doc = new PDFDocument();
    const filename = `RWH_Assessment_${Date.now()}.pdf`;
    const filepath = path.join(__dirname, '..', 'uploads', filename);
    
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);
    
    // Header
    doc.fontSize(24).text('Rooftop Rainwater Harvesting Assessment Report', 50, 50);
    doc.fontSize(12).text(`Generated on: ${new Date().toLocaleDateString()}`, 50, 90);
    
    // User Information
    doc.fontSize(16).text('User Information', 50, 130);
    doc.fontSize(11);
    doc.text(`Name: ${userInfo.name || 'N/A'}`, 50, 155);
    doc.text(`Location: ${userInfo.location || 'N/A'}`, 50, 170);
    doc.text(`State: ${userInfo.state || 'N/A'}`, 50, 185);
    
    // Assessment Summary
    doc.fontSize(16).text('Assessment Summary', 50, 220);
    doc.fontSize(11);
    doc.text(`Annual Rainfall: ${assessmentData.rainfall.annual} mm`, 50, 245);
    doc.text(`Roof Runoff Potential: ${assessmentData.runoff.potential.toLocaleString()} liters/year`, 50, 260);
    doc.text(`Feasibility Score: ${assessmentData.feasibility.score}/100 (${assessmentData.feasibility.rating})`, 50, 275);
    
    // Structure Recommendations
    doc.fontSize(16).text('Recommended Structure', 50, 310);
    doc.fontSize(11);
    const s = assessmentData.structure;
    if (s.type === 'Recharge Pit') {
      doc.text(`Type: ${s.type}`, 50, 335);
      doc.text(`Dimensions: ${s.length}m x ${s.width}m x ${s.depth}m`, 50, 350);
    } else if (s.type === 'Recharge Trench') {
      doc.text(`Type: ${s.type}`, 50, 335);
      doc.text(`Dimensions: ${s.length}m x ${s.width}m x ${s.depth}m`, 50, 350);
    } else {
      doc.text(`Type: ${s.type}`, 50, 335);
      doc.text(`Dimensions: ${s.diameter}m diameter x ${s.depth}m depth`, 50, 350);
    }
    doc.text(`Recharge Volume: ${s.volume.toLocaleString()} liters`, 50, 365);
    
    // Cost Analysis
    doc.fontSize(16).text('Cost Analysis', 50, 400);
    doc.fontSize(11);
    doc.text(`Structure Cost: ₹${assessmentData.costs.structure.toLocaleString()}`, 50, 425);
    doc.text(`Storage Cost: ₹${assessmentData.costs.storage.toLocaleString()}`, 50, 440);
    doc.text(`Annual Maintenance: ₹${assessmentData.costs.maintenance.toLocaleString()}`, 50, 455);
    doc.fontSize(12).text(`Total Investment: ₹${assessmentData.costs.total.toLocaleString()}`, 50, 475);
    
    // Benefits
    doc.fontSize(16).text('Expected Benefits', 50, 510);
    doc.fontSize(11);
    doc.text(`Annual Water Savings: ${assessmentData.benefits.annualWaterSavings.toLocaleString()} liters`, 50, 535);
    doc.text(`Annual Cost Savings: ₹${assessmentData.benefits.annualCostSavings.toLocaleString()}`, 50, 550);
    doc.text(`Groundwater Recharge: ${assessmentData.benefits.groundwaterRecharge.toLocaleString()} liters/year`, 50, 565);
    doc.text(`Payback Period: ${assessmentData.benefits.paybackPeriod} years`, 50, 580);
    
    // Recommendations
    doc.fontSize(16).text('Recommendations', 50, 615);
    doc.fontSize(11);
    let y = 640;
    assessmentData.recommendations.forEach((rec, idx) => {
      doc.text(`${idx + 1}. ${rec}`, 50, y);
      y += 20;
    });
    
    // Footer
    doc.fontSize(10).text('This report is generated by the Rooftop Rainwater Harvesting Assessment Application.', 50, 750);
    doc.text('Data sources: CGWB, IMD, and scientific publications on artificial recharge.', 50, 765);
    
    doc.end();
    
    stream.on('finish', () => {
      res.json({
        success: true,
        data: {
          downloadUrl: `/uploads/${filename}`,
          filename: filename
        }
      });
    });
    
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// POST /api/report/blueprint
router.post('/blueprint', async (req, res) => {
  try {
    const { assessmentData, userInfo } = req.body;
    
    const doc = new PDFDocument();
    const filename = `RWH_Blueprint_${Date.now()}.pdf`;
    const filepath = path.join(__dirname, '..', 'uploads', filename);
    
    const stream = fs.createWriteStream(filepath);
    doc.pipe(stream);
    
    // Title
    doc.fontSize(24).text('DIY Installation Blueprint', 50, 50);
    doc.fontSize(14).text('Complete Guide for Rooftop Rainwater Harvesting System', 50, 80);
    
    // Bill of Materials
    doc.fontSize(16).text('Bill of Materials', 50, 120);
    doc.fontSize(10);
    
    const bom = [
      { item: 'Rainwater Filter', qty: 1, unit: 'nos', price: 8500 },
      { item: 'Storage Tank', qty: Math.ceil(assessmentData.storage.required / 1000), unit: 'nos', price: 8000 },
      { item: 'PVC Pipes (3 inch)', qty: Math.ceil(Math.sqrt(assessmentData.runoff.potential / 100)), unit: 'meters', price: 180 },
      { item: 'Gutter System', qty: Math.ceil(Math.sqrt(assessmentData.runoff.potential / 50)), unit: 'meters', price: 250 },
      { item: 'First Flush Diverter', qty: 1, unit: 'nos', price: 2200 },
      { item: 'Gravel (for recharge)', qty: Math.ceil(assessmentData.structure.volume / 1000), unit: 'cubic meters', price: 1500 },
      { item: 'Sand', qty: Math.ceil(assessmentData.structure.volume / 2000), unit: 'cubic meters', price: 800 },
      { item: 'Cement', qty: 10, unit: 'bags', price: 400 },
      { item: 'Labor (skilled)', qty: 5, unit: 'days', price: 1200 },
      { item: 'Labor (unskilled)', qty: 10, unit: 'days', price: 800 }
    ];
    
    let y = 145;
    let totalCost = 0;
    
    doc.text('Item', 50, y);
    doc.text('Qty', 300, y);
    doc.text('Unit', 350, y);
    doc.text('Price', 450, y);
    doc.text('Amount', 520, y);
    
    y += 20;
    doc.moveTo(50, y - 5).lineTo(580, y - 5).stroke();
    
    bom.forEach(item => {
      const amount = item.qty * item.price;
      totalCost += amount;
      doc.text(item.item, 50, y);
      doc.text(item.qty.toString(), 300, y);
      doc.text(item.unit, 350, y);
      doc.text(`₹${item.price}`, 450, y);
      doc.text(`₹${amount.toLocaleString()}`, 520, y);
      y += 18;
    });
    
    doc.moveTo(50, y - 5).lineTo(580, y - 5).stroke();
    doc.fontSize(12).text(`Total Estimated Cost: ₹${totalCost.toLocaleString()}`, 350, y + 10);
    
    // Installation Steps
    y += 50;
    doc.fontSize(16).text('Installation Steps', 50, y);
    y += 30;
    
    doc.fontSize(11);
    const steps = [
      'Step 1: Site Preparation - Clear the area and mark dimensions',
      'Step 2: Gutter Installation - Install gutters along roof edges',
      'Step 3: Downpipe Setup - Connect downpipes to gutters',
      'Step 4: Filter Installation - Install first flush diverter and filter',
      'Step 5: Storage Tank - Position and connect storage tank',
      'Step 6: Recharge Structure - Excavate and construct recharge pit/trench',
      'Step 7: Overflow Management - Connect overflow to recharge structure',
      'Step 8: Testing - Test the complete system with water'
    ];
    
    steps.forEach(step => {
      doc.text(step, 50, y);
      y += 20;
    });
    
    // Technical Specifications
    y += 20;
    doc.fontSize(16).text('Technical Specifications', 50, y);
    y += 30;
    doc.fontSize(10);
    
    doc.text(`Structure Type: ${assessmentData.structure.type}`, 50, y);
    doc.text(`Storage Capacity: ${assessmentData.storage.required.toLocaleString()} liters`, 50, y + 15);
    doc.text(`Expected Runoff: ${assessmentData.runoff.potential.toLocaleString()} liters/year`, 50, y + 30);
    doc.text(`Soil Type: ${assessmentData.soil.structure}`, 50, y + 45);
    
    doc.end();
    
    stream.on('finish', () => {
      res.json({
        success: true,
        data: {
          downloadUrl: `/uploads/${filename}`,
          filename: filename,
          billOfMaterials: bom,
          estimatedCost: totalCost
        }
      });
    });
    
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

module.exports = router;
